### Deploy-node_exporter vars
nodeexp_dir: /apps/node_exporter
nodeexp_service_file: node_exporter.service
nodeexp_systemd_path: /etc/systemd/system
nodeexp_url: https://
nodeexp_archive: node_exporter-1.3.1.linux-amd64.tar.gz
nodeexp_file: node_exporter-1.3.1.linux-amd64
### Deploy-vmagent vars
vm_token: "{{ lookup('hashi_vault', '{{ vault_vmagent_token_path }} auth_method=ldap mount_point=ldap username={{ vault_login }} password={{ ipa_password }} url={{ vault_path }} validate_certs=True cacert=/etc/ssl/certs/ca-bundle.crt')}}"
vault_vmagent_token_path: "secret="
vm_env: "prod"
vmagent: vmagent-db.yaml
vmagent_url: https://
vmagent_archive: vmutils-linux-amd64-v1.91.3.tar.gz
vm_path: "/apps/vmagent_systemd"
vm_user: ""
vm_group: ""
relabel: "relabel.yml"
env: ".env"
vm_service: "vmagent.service"
system_path: "/etc/systemd/system"
### Vault vars
vault_path: "https://"
vault_login:
