### Deploy blackbox_exporter vars
blackbox_dir: /apps/blackbox_exporter
blackbox_url: https://
blackbox_package: prometheus-blackbox-exporter_0.19.0-1_amd64.deb
blackbox_service_file: prometheus-blackbox-exporter.service
blackbox_systemd_path: /etc/systemd/system/multi-user.target.wants
blackbox_targets:
  - https://
  - https://
  - https://
blackbox_file: blackbox.yaml
vm_url: ""

