### Deploy keepalived_exporter vars
keep_systemd_path: /etc/systemd/system
keep_dir: /apps/keepalived_exporter
keep_file: keepalived-exporter-1.2.0.linux-amd64
keep_service_file: keepalived_exporter.service
keep_url: https://
keep_archive: keepalived-exporter-1.2.0.linux-amd64.tar.gz
### Deploy mtail vars
mtail_dir: /apps/mtail
mtail_service_file: mtail.service
mtail_systemd_path: /etc/systemd/system
mtail_url: https://
mtail_archive: mtail_3.0.0-rc51_Linux_x86_64.tar.gz
### Deploy-nginx-configs vars
nginx_path: /etc/nginx
server_path: /etc/nginx/conf.d
nginx: nginx.conf
nginx_portal: nginx_portal_prod.conf
mirage_portal: mirage_portal_prod.conf
nginx_front: nginx_front_prod.conf
mirage_front: mirage_front_prod.conf
### Deploy Certs vars
nginx_cert_path: /etc/pki/nginx
vault_path: "https://"
vault_login:
vault_nginx_cert_path: "secret="
vault_nginx_key_path: "secret="
vault_bundle_path: "secret="
nginx_cert: p_m_proxy_ID.cer
nginx_key: p_m_proxy_ID.key
bundle_file: bundle_prod.cer
### Deploy logrotate vars
logrotate_file: nginx
logrotate_path: /etc/logrotate.d
arch_dir: /apps/nginx_log/arch
period: daily
owner: "0644 www-data adm"
dateformat: "-%Y%m%d-%H%M%S"
odldir path: "/apps/nginx_log/arch"
rotate_perido: 30
su_command: "su www-data adm"
### vmagent file
vmagent: vmagent-nginx.yaml

